# This is a basic workflow to help you get started with Actions

name: CI for cypress-training

on: 
  pull_request:
  push:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"

      - name: Install
        run: npm ci

      - name: Code style
        run: npm run lint

      - name: UI E2E Tests
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headed: true
